version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: ts-loader
    versions:
    - 8.0.14
    - 8.0.15
    - 8.0.16
    - 8.0.17
    - 8.0.18
    - 8.1.0
    - 9.0.0
    - 9.1.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: "@types/webpack"
    versions:
    - 4.41.26
    - 5.0.0
  - dependency-name: "@types/koa"
    versions:
    - 2.11.7
    - 2.11.8
    - 2.13.0
  - dependency-name: typescript
    versions:
    - 3.9.7
    - 3.9.8
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
